name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Build and Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v2
        env:
          ACCESS_TOKEN: ${{ secrets.TOKEN }}
          BASE_BRANCH: main
          BRANCH: main
          FOLDER: dist/sorour.works
          BUILD_SCRIPT: npm install && npm run build -- --prod
