name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 8.15.1
        uses: actions/setup-node@v1
        with:
          node-version: 8.15.1
      - name: Build and Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v2
        env:
          ACCESS_TOKEN: ${{ secrets.OKEN }}
          BASE_BRANCH: main
          BRANCH: main
          FOLDER: dist/sorour.works
          BUILD_SCRIPT: npm install && npm run build -- --prod
